### ISSUE TITLE
Order autocomplete results

### ISSUE THREAD

**Issue by karniv00l** [hyper-tuner/hypertuner-cloud#846]
Order by occurrence (more common - higher in the list)

**Comment by mi-hol** [comment]
where do you see this feature to be added (i.e. src/components/Tune/Dialog/TextField.tsx)?

**Comment by karniv00l** [comment]
This is in tune's details section when uploading or editing

<img width="675" alt="Screenshot 2023-08-11 at 15 27 06" src="https://github.com/hyper-tuner/hypertuner-cloud/assets/3144291/ed82f90c-1e05-4315-9ed3-386867ee0c6b">

**Comment by mi-hol** [comment]
People not familiar with code base (beginners) would greatly benefit from knowing the file name :)

**Comment by mi-hol** [comment]
Suspect file hypertuner-cloud/src/pages/Upload.tsx

code block:
```

          <Item name='engineMake' rules={requiredTextRules}>
            <AutoComplete
              options={autocompleteOptions.engineMake}
              onSearch={(search) => searchAutocomplete('engineMake', search)}
              backfill
```

Correct?

**Comment by karniv00l** [comment]
To be specific: https://github.com/hyper-tuner/hypertuner-cloud/blob/master/src/pages/Upload.tsx#L153

**Comment by mi-hol** [comment]
ok, so it seems first hurdle to understanding requirement(s) was taken.

Paraphrased in my words:
Envisaged is a global change affecting all text input fields based on count of existing values in hypertuner dataset, **without** considering user specific count of previously used values.

Correct?

**Comment by karniv00l** [comment]
Yes, at least this is what I was thinking when creating this issue

for example: more popular "make" -> higher in the autocomplete list in "make" field

**Comment by karniv00l** [comment]
ChatGPTs anwser:

```ts
const options = (await autocomplete(attribute, search)).map((record) => record[attribute]);

// Count the occurrences of each value
const valueCounts = {};
options.forEach((value) => {
  valueCounts[value] = (valueCounts[value] || 0) + 1;
});

// Sort values by occurrence frequency (more common - higher in the list)
const unique = [...new Set(options)].map((value) => ({ value })).sort((a, b) => valueCounts[b.value] - valueCounts[a.value]);
```

**Comment by mi-hol** [comment]
ok, so does this ths code work as expected?

On a somewhat related topic, is it desired to have the same engine multiple times in the dataset under the  different car maker brands using it in different model?
Best example is the famous DieselGate [EA 189 engine](https://en.wikipedia.org/wiki/EA_189).
This engine is found in cars from VW, AUDI, Porsche  and the count of multi-brand engines is growing strong after 2003.

**Comment by karniv00l** [comment]
I haven't checked the code 

Regarding other topic, it's and idea, but I'm not sure whether it's worth the time at this stage. However it could be nice to pull data from a good source

**Comment by karniv00l** [comment]
It appears to be already handled internally by the `<AutoComplete />` component. Thanks @villager88 !
